language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.6"
env:
  - SECRET_KEY=secretkey
install:
  - pip install -r requirements.txt
script:
  - python manage.py runserver
  - python crossvalidation0.py
  - python crossvalidation1.py
  - python crossvalidation1_stopwords.py
  - python crossvalidation.py
  - python feature_selection_ka2.py
  - python feature_selection.py
  - python feature_selection_all.py
  - python eval.py
  - python naivebayes.py
  - python trans_data.py
