language: python
env:
  - DJANGO_VERSION=1.11.3
python:
  - "3.6"

before_install:
# テストに必要な環境を整える
  - pip install -r requirements-dev.txt

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install --upgrade setuptools
  - pip install ez_setup
  - python setup.py -q install
  - pip install .
  #- pip install -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py test
  - invoke test
