language: python
env:
  - DJANGO_VERSION=1.11.3
python:
  - "3.6"
#before_install:
#  - sudo apt-get update
#  - sudo apt-get -y install python-pip
#  - sudo pip install --upgrade pip
#  - pip install --upgrade pip
#  - pip install pep8
#  - pip install autopep8
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install --upgrade setuptools
  - pip install ez_setup
  - python setup.py -q install
  - pip install .
  - pip install --user -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py test
